// Run with: node --test tests/js/*.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import {
  parseParams,
  uniformDeclarations,
  setParamDefaults,
  renderSettings,
  hexToRgb,
} from "../../autofx/editor/params.js";

const cases = JSON.parse(
  readFileSync(new URL("../param_cases.json", import.meta.url), "utf8"),
);

for (const c of cases.valid) {
  test(`parses: ${c.name}`, () => {
    const { params, errors } = parseParams(c.source);
    assert.deepEqual(errors, []);
    assert.deepEqual(params, c.params);
  });
}

for (const c of cases.invalid) {
  test(`rejects: ${c.name}`, () => {
    const { errors } = parseParams(c.source);
    assert.ok(errors.some((e) => e.includes(c.error)), JSON.stringify(errors));
  });
}

test("uniform declarations map color to vec3", () => {
  const { params } = parseParams(
    "// @param speed float 1 [0, 2]\n// @param tint color #ff0000\n// @param n int 3 [1, 9]",
  );
  assert.equal(
    uniformDeclarations(params),
    "uniform float speed;\nuniform vec3 tint;\nuniform int n;\n",
  );
});

test("hexToRgb converts to 0-1 floats", () => {
  assert.deepEqual(hexToRgb("#ff0080"), [1, 0, 128 / 255]);
});

test("setParamDefaults rewrites defaults and keeps everything else", () => {
  const source = [
    "// Generated by: autofx 'torch' --loop",
    "  // @param speed float 1.0 [0.1, 4.0] \"Animation speed\"",
    "// @param tint color #ff0000",
    "// @param wind vec2 (0.2, 0.0) [-1, 1] \"Wind\"",
    "// @param glow bool true",
    "void mainImage(out vec4 c, in vec2 p) { c = vec4(tint * speed, 1.0); }",
  ].join("\n");
  const updated = setParamDefaults(source, {
    speed: 2.25,
    tint: "#00ff80",
    wind: [-0.5, 0.125],
    glow: false,
  });
  assert.equal(
    updated,
    [
      "// Generated by: autofx 'torch' --loop",
      "  // @param speed float 2.25 [0.1, 4] \"Animation speed\"",
      "// @param tint color #00ff80",
      "// @param wind vec2 (-0.5, 0.125) [-1, 1] \"Wind\"",
      "// @param glow bool false",
      "void mainImage(out vec4 c, in vec2 p) { c = vec4(tint * speed, 1.0); }",
    ].join("\n"),
  );
  const { params } = parseParams(updated);
  assert.deepEqual(
    params.map((p) => p.default),
    [2.25, "#00ff80", [-0.5, 0.125], false],
  );
});

test("setParamDefaults keeps float defaults recognisable as floats", () => {
  const updated = setParamDefaults("// @param s float 1.5 [0, 4]", { s: 3 });
  assert.equal(updated, "// @param s float 3.0 [0, 4]");
});

test("renderSettings reads duration, frames and loop from the header", () => {
  const source =
    "// Generated by: autofx 'torch flame' -f 30 --loop -o torch.gif\n" +
    "// Render with:  autofx torch.glsl -d 1.5 -r 256x256 -f 30 -o torch.gif\n";
  assert.deepEqual(renderSettings(source), {
    duration: 1.5,
    frames: 30,
    loop: true,
    width: 256,
    height: 256,
  });
});

test("renderSettings falls back to CLI defaults without a header", () => {
  assert.deepEqual(renderSettings("void mainImage() {}"), {
    duration: 1,
    frames: 10,
    loop: false,
    width: 256,
    height: 256,
  });
});
