// Generated by: autofx --edit examples/magic-flames.glsl 'make the flames blue instead of purple' -d 1.5 -f 45 --loop -o /tmp/blue-flames.gif
// Render with:  autofx /tmp/blue-flames.glsl -d 1.5 -r 256x256 -f 45 --loop -o /tmp/blue-flames.gif

// Mystical Blue Flames with Magical Fire
// Looping duration: 1.5 seconds

#define PI 3.14159265359
#define TAU 6.28318530718
#define DURATION 1.5

// Hash function for noise
float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
}

// Smooth noise
float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    
    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));
    
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

// Fractal Brownian Motion
float fbm(vec2 p) {
    float value = 0.0;
    float amplitude = 0.5;
    float frequency = 1.0;
    mat2 rot = mat2(0.8, 0.6, -0.6, 0.8);
    
    for(int i = 0; i < 6; i++) {
        value += amplitude * noise(p * frequency);
        p = rot * p;
        amplitude *= 0.5;
        frequency *= 2.0;
    }
    return value;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    vec2 centered = uv - vec2(0.5);
    
    // Cycling time - completes exactly one cycle over DURATION
    float t = iTime * TAU / DURATION;
    float cyclePhase = fract(iTime / DURATION);
    
    // Edge fade for safe margins
    float edgeFade = smoothstep(0.0, 0.1, uv.x) * smoothstep(1.0, 0.9, uv.x) *
                     smoothstep(0.0, 0.08, uv.y) * smoothstep(1.0, 0.92, uv.y);
    
    // Flame coordinate system - move origin to bottom center
    vec2 flameUV = vec2(centered.x, uv.y - 0.15);
    
    // Add gentle swirl distortion (cyclic)
    float swirlAmount = sin(t) * 0.15;
    float swirlY = flameUV.y * 2.0;
    flameUV.x += sin(swirlY * 3.0 + t) * swirlAmount * swirlY;
    
    // Cyclic noise offset for animation
    vec2 noiseOffset = vec2(sin(t) * 0.5, -cos(t) * 2.0);
    
    // Multiple noise layers for flame turbulence
    float noise1 = fbm(flameUV * 4.0 + noiseOffset);
    float noise2 = fbm(flameUV * 8.0 + noiseOffset * 1.5);
    float noise3 = fbm(flameUV * 12.0 + noiseOffset * 0.7);
    float flameNoise = noise1 * 0.5 + noise2 * 0.3 + noise3 * 0.2;
    
    // Flame base shape - tapers toward top
    float flameWidth = 0.28 * (1.0 - flameUV.y * 0.7);
    flameWidth *= 1.0 + 0.15 * sin(t * 2.0); // Breathing effect
    
    // Add noise to flame edges
    float edgeNoise = (flameNoise - 0.5) * 0.15 * (0.5 + flameUV.y);
    float flameShape = smoothstep(flameWidth + edgeNoise, 0.0, abs(flameUV.x));
    
    // Vertical envelope
    float flameHeight = smoothstep(0.0, 0.15, flameUV.y) * smoothstep(0.85, 0.3, flameUV.y);
    
    // Combine for base flame
    float flame = flameShape * flameHeight;
    flame *= 0.7 + 0.5 * flameNoise;
    
    // Inner core - white hot center
    float coreWidth = 0.12 * (1.0 - flameUV.y * 1.2);
    coreWidth *= 0.9 + 0.1 * sin(t * 3.0);
    float core = smoothstep(coreWidth, 0.0, abs(flameUV.x));
    core *= smoothstep(0.0, 0.1, flameUV.y) * smoothstep(0.45, 0.1, flameUV.y);
    core *= 0.8 + 0.2 * noise1;
    
    // Secondary glow around core
    float innerGlow = smoothstep(0.2, 0.0, abs(flameUV.x));
    innerGlow *= smoothstep(0.0, 0.12, flameUV.y) * smoothstep(0.55, 0.15, flameUV.y);
    innerGlow *= 0.6;
    
    // Flickering flame tongues
    float tongues = 0.0;
    for(int i = 0; i < 5; i++) {
        float fi = float(i);
        float phase = fi * TAU / 5.0;
        float tongueX = flameUV.x - (fi - 2.0) * 0.07;
        tongueX += sin(t * 2.0 + phase) * 0.025;
        
        float tongueHeight = 0.5 + 0.15 * sin(t * 2.5 + phase);
        float tongue = smoothstep(0.04, 0.0, abs(tongueX));
        tongue *= smoothstep(0.2, 0.25, flameUV.y) * smoothstep(tongueHeight, 0.3, flameUV.y);
        tongue *= 0.5 + 0.5 * sin(t * 3.0 + phase);
        tongues += tongue * 0.3;
    }
    
    // Ethereal wisps rising upward
    float wisps = 0.0;
    for(int i = 0; i < 10; i++) {
        float fi = float(i);
        float wispPhase = fi * 0.628318; // TAU/10
        float wispTime = fract(cyclePhase + fi * 0.1);
        
        // Wisp rises and sways
        float wispX = 0.5 + sin(wispPhase) * 0.12;
        wispX += sin(t + fi * 0.7) * 0.04 * wispTime;
        float wispY = mix(0.4, 0.9, wispTime);
        
        // Wisp shape
        vec2 wispDelta = (uv - vec2(wispX, wispY)) * vec2(5.0, 1.5);
        float wispDist = length(wispDelta);
        
        // Fade in and out for seamless loop
        float wispFade = sin(wispTime * PI);
        wispFade = wispFade * wispFade;
        
        float wisp = smoothstep(0.12, 0.0, wispDist) * wispFade;
        wisp *= 0.6 + 0.4 * sin(t * 2.0 + fi);
        wisps += wisp * 0.2;
    }
    
    // Magical sparkles
    float sparkles = 0.0;
    for(int i = 0; i < 12; i++) {
        float fi = float(i);
        float sparkPhase = fi * 0.523599;
        float sparkTime = fract(cyclePhase + fi * 0.0833);
        
        float sparkX = 0.5 + sin(sparkPhase * 2.0 + fi) * 0.18;
        sparkX += sin(t * 2.0 + fi) * 0.03;
        float sparkY = mix(0.2, 0.8, sparkTime);
        
        float sparkDist = length(uv - vec2(sparkX, sparkY));
        float sparkle = smoothstep(0.015, 0.0, sparkDist);
        sparkle *= sin(sparkTime * PI); // Fade in/out
        sparkle *= 0.3 + 0.7 * sin(t * 8.0 + fi * 2.0); // Twinkle
        sparkles += sparkle;
    }
    
    // Color palette - mystical blue
    vec3 deepBlue = vec3(0.02, 0.05, 0.3);
    vec3 blue = vec3(0.05, 0.2, 0.7);
    vec3 brightBlue = vec3(0.1, 0.4, 0.9);
    vec3 cyan = vec3(0.3, 0.7, 1.0);
    vec3 lightCyan = vec3(0.6, 0.9, 1.0);
    vec3 white = vec3(0.95, 0.98, 1.0);
    vec3 wispBlue = vec3(0.4, 0.6, 0.95);
    
    // Build color based on intensity
    vec3 col = vec3(0.0);
    
    float intensity = flame + tongues * flameNoise;
    
    // Layer colors from outer to inner
    col = mix(col, deepBlue, smoothstep(0.0, 0.15, intensity));
    col = mix(col, blue, smoothstep(0.1, 0.3, intensity));
    col = mix(col, brightBlue, smoothstep(0.25, 0.5, intensity));
    col = mix(col, cyan, smoothstep(0.4, 0.7, intensity));
    col = mix(col, lightCyan, smoothstep(0.6, 0.85, intensity));
    
    // Inner glow
    col = mix(col, lightCyan, innerGlow * 0.6);
    
    // White hot core
    col = mix(col, white, core * 0.9);
    
    // Wisps
    col = mix(col, wispBlue, wisps * 0.8);
    
    // Sparkles
    col += vec3(0.8, 0.95, 1.0) * sparkles;
    
    // Calculate alpha
    float alpha = intensity + core * 0.8 + innerGlow * 0.4 + wisps * 0.6 + sparkles * 0.5;
    alpha = clamp(alpha, 0.0, 1.0);
    
    // Apply edge fade
    alpha *= edgeFade;
    
    // Subtle outer glow
    float glow = flame * 0.4;
    col += vec3(0.1, 0.2, 0.5) * glow * 0.2;
    
    fragColor = vec4(col, alpha);
}