// Generated by: autofx 'colorful particle explosion with sparks flying in random directions' -f 30 -n 3 -o examples/particle-burst.gif
// Render with:  autofx examples/particle-burst.glsl -d 1.0 -r 256x256 -f 30 -o examples/particle-burst.gif

// Colorful particle explosion with sparks - Enhanced version
// Uses iSeed for variation

// Hash functions for randomness
float hash(float n) {
    return fract(sin(n + iSeed * 127.1) * 43758.5453123);
}

float hash2(vec2 p) {
    return fract(sin(dot(p + iSeed, vec2(127.1, 311.7))) * 43758.5453123);
}

// HSV to RGB conversion
vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    vec2 center = vec2(0.5, 0.5);
    vec2 pos = uv - center;
    
    float t = iTime;
    
    // Global fade out - ensure complete transparency at t=1.0
    float globalFade = 1.0 - smoothstep(0.5, 1.0, t);
    globalFade = pow(globalFade, 1.5);
    
    vec3 color = vec3(0.0);
    float alpha = 0.0;
    
    // Central flash at explosion start
    float flashTime = 0.12;
    float flash = smoothstep(0.0, 0.03, t) * smoothstep(flashTime, 0.01, t);
    float flashDist = length(pos);
    float flashIntensity = flash * smoothstep(0.2, 0.0, flashDist);
    vec3 flashColor = vec3(1.0, 0.95, 0.7);
    color += flashColor * flashIntensity * 3.0;
    alpha += flashIntensity * 1.5;
    
    // Main colorful particles - larger, more dramatic
    const int NUM_PARTICLES = 60;
    for(int i = 0; i < NUM_PARTICLES; i++) {
        float fi = float(i);
        
        // Random angle with seed variation
        float angle = hash(fi * 13.37) * 6.28318;
        angle += iSeed * 2.1; // Rotate entire explosion pattern
        
        // Random speed
        float speed = 0.25 + hash(fi * 7.13 + iSeed * 33.0) * 0.35;
        
        vec2 dir = vec2(cos(angle), sin(angle));
        
        // Particle position with deceleration
        float particleT = t;
        float decel = exp(-particleT * 3.0);
        vec2 particlePos = dir * speed * particleT * (1.0 + decel);
        
        // Slight gravity effect
        particlePos.y -= 0.15 * particleT * particleT;
        
        // Keep within bounds
        float maxDist = 0.38;
        float currentDist = length(particlePos);
        if(currentDist > maxDist) {
            particlePos *= maxDist / currentDist;
        }
        
        // Particle size - larger initially, shrinks
        float baseSize = 0.025 + hash(fi * 3.21) * 0.02;
        float size = baseSize * (1.0 - t * 0.6);
        
        float dist = length(pos - particlePos);
        
        // Soft particle with glow
        float intensity = smoothstep(size, size * 0.1, dist);
        intensity += 0.6 * smoothstep(size * 2.5, size * 0.3, dist);
        
        // Vibrant colors - spread across hue spectrum with seed offset
        float hue = fract(fi * 0.08 + iSeed * 0.25 + hash(fi * 99.0) * 0.3);
        vec3 particleColor = hsv2rgb(vec3(hue, 0.9, 1.0));
        
        // Fade particle over its lifetime
        float lifespan = 1.0 - smoothstep(0.2, 0.85, t);
        intensity *= lifespan;
        
        color += particleColor * intensity * 0.6;
        alpha += intensity * 0.35;
    }
    
    // Small bright sparks - fast moving
    const int NUM_SPARKS = 100;
    for(int i = 0; i < NUM_SPARKS; i++) {
        float fi = float(i);
        
        // Random direction with seed variation
        float angle = hash(fi * 23.45 + 100.0) * 6.28318 + iSeed * 1.8;
        float speed = 0.5 + hash(fi * 11.23 + 200.0 + iSeed * 50.0) * 0.7;
        
        // Staggered start times for more dynamic feel
        float startDelay = hash(fi * 5.67) * 0.08;
        float sparkT = max(0.0, t - startDelay);
        
        vec2 dir = vec2(cos(angle), sin(angle));
        
        // Spark trajectory with stronger gravity
        float gravity = -0.5 * sparkT * sparkT;
        vec2 sparkPos = dir * speed * sparkT * exp(-sparkT * 2.0);
        sparkPos.y += gravity * 0.4;
        
        // Bound the sparks
        float maxSparkDist = 0.4;
        float sparkDist = length(sparkPos);
        if(sparkDist > maxSparkDist) {
            sparkPos *= maxSparkDist / sparkDist;
        }
        
        // Very small spark points
        float sparkSize = 0.006 + hash(fi * 9.87 + iSeed) * 0.006;
        sparkSize *= max(0.0, 1.0 - t * 1.2);
        
        float dist = length(pos - sparkPos);
        
        // Sharp bright spark with small glow
        float sparkIntensity = smoothstep(sparkSize, 0.0, dist);
        sparkIntensity += 0.4 * smoothstep(sparkSize * 3.0, sparkSize * 0.5, dist);
        
        // Spark colors - warm yellows, oranges, whites with some color variation
        float colorChoice = hash(fi * 4.56 + iSeed * 20.0);
        vec3 sparkColor;
        if(colorChoice < 0.5) {
            // Warm spark (yellow/orange/white)
            sparkColor = mix(vec3(1.0, 0.9, 0.4), vec3(1.0, 0.6, 0.2), colorChoice * 2.0);
        } else {
            // Match nearby particle color for variety
            float hue = fract(fi * 0.05 + iSeed * 0.3);
            sparkColor = hsv2rgb(vec3(hue, 0.7, 1.0));
        }
        sparkColor = mix(sparkColor, vec3(1.0), 0.4); // Brighten
        
        // Flicker effect
        float flicker = 0.6 + 0.4 * sin(fi * 25.0 + t * 40.0 + iSeed * 15.0);
        sparkIntensity *= flicker;
        
        // Fade based on lifetime
        float sparkLife = 1.0 - smoothstep(0.15, 0.9, t);
        sparkIntensity *= sparkLife;
        
        color += sparkColor * sparkIntensity * 0.7;
        alpha += sparkIntensity * 0.5;
    }
    
    // Trailing ember particles - slower, fall down
    const int NUM_EMBERS = 40;
    for(int i = 0; i < NUM_EMBERS; i++) {
        float fi = float(i);
        
        float angle = hash(fi * 31.17 + 500.0) * 6.28318 + iSeed * 0.7;
        float speed = 0.15 + hash(fi * 17.31 + iSeed * 70.0) * 0.2;
        
        float emberT = max(0.0, t - 0.05);
        vec2 dir = vec2(cos(angle), sin(angle));
        
        // Embers fly out then fall
        vec2 emberPos = dir * speed * emberT * exp(-emberT * 1.5);
        emberPos.y -= 0.3 * emberT * emberT; // Stronger gravity
        
        // Bound
        float maxEmberDist = 0.35;
        float emberDist = length(emberPos);
        if(emberDist > maxEmberDist) {
            emberPos *= maxEmberDist / emberDist;
        }
        
        float emberSize = 0.008 + hash(fi * 7.77) * 0.008;
        emberSize *= max(0.0, 1.0 - t * 1.1);
        
        float dist = length(pos - emberPos);
        float emberIntensity = smoothstep(emberSize, emberSize * 0.2, dist);
        emberIntensity += 0.3 * smoothstep(emberSize * 2.5, emberSize, dist);
        
        // Ember colors - oranges and reds
        float emberHue = 0.02 + hash(fi * 8.88 + iSeed) * 0.08;
        vec3 emberColor = hsv2rgb(vec3(emberHue, 0.9, 1.0));
        
        // Pulsing glow
        float pulse = 0.5 + 0.5 * sin(fi * 10.0 + t * 20.0 + iSeed * 8.0);
        emberIntensity *= pulse;
        
        // Fade
        float emberLife = 1.0 - smoothstep(0.3, 0.95, t);
        emberIntensity *= emberLife;
        
        color += emberColor * emberIntensity * 0.5;
        alpha += emberIntensity * 0.3;
    }
    
    // Apply global fade
    color *= globalFade;
    alpha *= globalFade;
    
    // Hard cutoff at the very end to ensure transparency
    if(t > 0.95) {
        float endFade = 1.0 - smoothstep(0.95, 1.0, t);
        color *= endFade;
        alpha *= endFade;
    }
    
    // Clamp
    alpha = clamp(alpha, 0.0, 1.0);
    color = clamp(color, 0.0, 1.0);
    
    fragColor = vec4(color, alpha);
}
