"""
Command-line interface for AutoFX.

Usage:
    autofx "fiery explosion" --duration 1.0 --resolution 256x256 --frames 10 -o explosion.gif

    # Re-render from existing shader:
    autofx explosion.glsl -r 512x512 -f 60 -o explosion_hd.gif
"""

import argparse
import asyncio
import shlex
import sys
import time as time_mod
from pathlib import Path
from typing import Tuple, Optional


def parse_resolution(value: str) -> Tuple[int, int]:
    """Parse resolution string like '256x256' into (width, height) tuple."""
    try:
        parts = value.lower().split('x')
        if len(parts) != 2:
            raise ValueError
        width, height = int(parts[0]), int(parts[1])
        if width <= 0 or height <= 0:
            raise ValueError
        return width, height
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"Invalid resolution '{value}'. Use format WIDTHxHEIGHT (e.g., 256x256)"
        )


def build_generate_command(args: argparse.Namespace) -> str:
    """Build the command string used to generate this shader."""
    parts = ["autofx", shlex.quote(args.prompt)]

    if args.duration != 1.0:
        parts.extend(["-d", str(args.duration)])
    if args.resolution != (256, 256):
        parts.extend(["-r", f"{args.resolution[0]}x{args.resolution[1]}"])
    if args.frames != 10:
        parts.extend(["-f", str(args.frames)])
    if args.loop:
        parts.append("--loop")
    if args.variations > 1:
        parts.extend(["-n", str(args.variations)])
    if args.spritesheet:
        parts.append("-s")
        if args.rows:
            parts.extend(["--rows", str(args.rows)])
    parts.extend(["-o", shlex.quote(args.output)])

    return " ".join(parts)


def build_render_command(shader_path: str, args: argparse.Namespace, output_path: Optional[str] = None) -> str:
    """Build a command to re-render from the shader file."""
    parts = ["autofx", shlex.quote(shader_path)]

    parts.extend(["-d", str(args.duration)])
    parts.extend(["-r", f"{args.resolution[0]}x{args.resolution[1]}"])
    parts.extend(["-f", str(args.frames)])
    if args.loop:
        parts.append("--loop")
    if args.spritesheet:
        parts.append("-s")
        if args.rows:
            parts.extend(["--rows", str(args.rows)])

    out = output_path or args.output
    parts.extend(["-o", shlex.quote(out)])

    return " ".join(parts)


def add_glsl_header(shader_code: str, generate_cmd: str, render_cmd: str) -> str:
    """Add command comments to the top of shader code."""
    header = f"""// Generated by: {generate_cmd}
// Render with:  {render_cmd}

"""
    return header + shader_code


def strip_glsl_header(shader_code: str) -> str:
    """Remove command comments from shader code if present."""
    lines = shader_code.split('\n')
    # Skip lines that start with "// Generated by:" or "// Render with:"
    while lines and (lines[0].startswith('// Generated by:') or
                     lines[0].startswith('// Render with:') or
                     lines[0].strip() == ''):
        lines.pop(0)
    return '\n'.join(lines)


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    parser = argparse.ArgumentParser(
        prog="autofx",
        description="Generate visual effects animations using AI-powered GLSL shaders",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # One-shot effect (dissipates by end)
    autofx "fiery explosion" -o explosion.gif

    # Looping effect (seamless loop)
    autofx "magical flames" --loop -d 2.0 -o flames.gif

    # High-quality with more frames
    autofx "lightning strike" -d 1.0 -r 256x256 -f 60 -o lightning.gif

    # With PNG sprite sheet (auto grid layout)
    autofx "energy ball" -f 16 -s -o energy.gif

    # Sprite sheet with specific row count
    autofx "coin spin" --loop -f 8 -s --rows 1 -o coin.gif

    # Re-render from existing shader (no AI, just render)
    autofx explosion.glsl -r 512x512 -f 60 -o explosion_hd.gif

    # Generate sprite sheet from existing shader
    autofx explosion.glsl -s -o explosion.gif

The generated shader code is automatically saved alongside the GIF.
For example, explosion.gif will have explosion.glsl saved next to it.
With -s/--spritesheet, a PNG sprite sheet is also saved (e.g., explosion.png).
The .glsl file includes comments with the original command and a render command.
        """
    )

    parser.add_argument(
        "prompt",
        type=str,
        help="Description of the visual effect (e.g., 'fiery explosion'), or path to .glsl file to render"
    )

    parser.add_argument(
        "-d", "--duration",
        type=float,
        default=1.0,
        help="Animation duration in seconds (default: 1.0)"
    )

    parser.add_argument(
        "-r", "--resolution",
        type=parse_resolution,
        default=(256, 256),
        metavar="WxH",
        help="Output resolution as WIDTHxHEIGHT (default: 256x256)"
    )

    parser.add_argument(
        "-f", "--frames",
        type=int,
        default=10,
        help="Number of frames to generate (default: 10)"
    )

    parser.add_argument(
        "-o", "--output",
        type=str,
        default="output.gif",
        help="Output file path (default: output.gif)"
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print detailed progress messages"
    )

    parser.add_argument(
        "-l", "--loop",
        action="store_true",
        help="Create a seamlessly looping effect (default: one-shot effect that dissipates)"
    )

    parser.add_argument(
        "-s", "--spritesheet",
        action="store_true",
        help="Also output a PNG sprite sheet (all frames in a grid)"
    )

    parser.add_argument(
        "--rows",
        type=int,
        default=None,
        help="Number of rows in sprite sheet (default: auto-calculated for square-ish layout)"
    )

    parser.add_argument(
        "-n", "--variations",
        type=int,
        default=1,
        help="Number of variations to generate with different random seeds (default: 1)"
    )

    parser.add_argument(
        "-m", "--model",
        type=str,
        default=None,
        help="Model to use for generation (default: claude-opus-4-5-20251101)"
    )

    parser.add_argument(
        "-e", "--edit",
        type=str,
        metavar="GLSL_FILE",
        default=None,
        help="Edit an existing shader with the given modification prompt"
    )

    return parser


async def run_async(args: argparse.Namespace) -> int:
    """Run the VFX generation asynchronously."""
    from .agent import generate_vfx
    from .gif import save_gif, save_spritesheet, get_spritesheet_layout
    from .renderer import render_shader
    from .timing import get_timer, reset_timer

    # Ensure output path has .gif extension
    output_path = args.output
    if not output_path.lower().endswith('.gif'):
        output_path += '.gif'

    print(f"Generating VFX: {args.prompt}")
    print(f"  Resolution: {args.resolution[0]}x{args.resolution[1]}")
    print(f"  Duration: {args.duration}s")
    print(f"  Frames: {args.frames}")
    print(f"  Mode: {'looping' if args.loop else 'one-shot (dissipates)'}")
    if args.variations > 1:
        print(f"  Variations: {args.variations}")
    if args.model:
        print(f"  Model: {args.model}")
    print(f"  Output: {output_path}")
    if args.spritesheet:
        cols, rows = get_spritesheet_layout(args.frames, args.rows)
        print(f"  Sprite sheet: {cols}x{rows} grid")
    print()

    reset_timer()
    timer = get_timer()
    timer.start()

    try:
        result = await generate_vfx(
            prompt=args.prompt,
            duration=args.duration,
            resolution=args.resolution,
            frames=args.frames,
            output_path=output_path,
            verbose=args.verbose,
            loop=args.loop,
            variations=args.variations,
            model=args.model
        )

        if result["success"]:
            print()
            print("Success!")

            shader_code = result.get("shader_code")
            output_base = Path(output_path)

            if args.variations > 1 and shader_code:
                # Multiple variations: rename original and render additional variations
                import os

                # Rename the original GIF (seed 0) to include -0 suffix
                original_gif = output_base
                variation_gif = output_base.with_stem(f"{output_base.stem}-0")
                if original_gif.exists():
                    os.rename(original_gif, variation_gif)
                print(f"  GIF: {variation_gif}")

                # Generate sprite sheet for variation 0 if requested
                if args.spritesheet:
                    spritesheet_path = variation_gif.with_suffix('.png')
                    frames = render_shader(
                        shader_code=shader_code,
                        duration=args.duration,
                        resolution=args.resolution,
                        num_frames=args.frames,
                        seed=0.0
                    )
                    cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                    print(f"  Sprite sheet: {spritesheet_path}")

                # Render additional variations with different seeds
                for i in range(1, args.variations):
                    variation_gif = output_base.with_stem(f"{output_base.stem}-{i}")
                    print(f"  Rendering variation {i}...")

                    frames = render_shader(
                        shader_code=shader_code,
                        duration=args.duration,
                        resolution=args.resolution,
                        num_frames=args.frames,
                        seed=float(i)
                    )

                    save_gif(frames, str(variation_gif), args.duration)
                    print(f"  GIF: {variation_gif}")

                    # Generate sprite sheet for this variation if requested
                    if args.spritesheet:
                        spritesheet_path = variation_gif.with_suffix('.png')
                        cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                        print(f"  Sprite sheet: {spritesheet_path}")

                # Shader is saved once without suffix
                print(f"  Shader: {result['shader_path']}")
            else:
                # Single variation: keep original behavior
                print(f"  GIF: {result['gif_path']}")
                print(f"  Shader: {result['shader_path']}")

                # Generate sprite sheet if requested
                if args.spritesheet and shader_code:
                    spritesheet_path = Path(output_path).with_suffix('.png')
                    print(f"  Generating sprite sheet...")

                    frames = render_shader(
                        shader_code=shader_code,
                        duration=args.duration,
                        resolution=args.resolution,
                        num_frames=args.frames
                    )

                    cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                    sheet_width = cols * args.resolution[0]
                    sheet_height = rows * args.resolution[1]
                    print(f"  Sprite sheet: {spritesheet_path} ({sheet_width}x{sheet_height}, {cols}x{rows} grid)")

            # Re-save shader with header comments
            shader_path = Path(output_path).with_suffix('.glsl')
            if shader_code and shader_path.exists():
                generate_cmd = build_generate_command(args)
                render_cmd = build_render_command(str(shader_path), args)
                shader_with_header = add_glsl_header(shader_code, generate_cmd, render_cmd)
                shader_path.write_text(shader_with_header)

            print(timer.summary())
            return 0
        else:
            print()
            print(f"Error: {result['error']}")
            return 1

    except ImportError as e:
        print(f"Error: {e}")
        print()
        print("Make sure you have the required dependencies installed:")
        print("  pip install claude-agent-sdk moderngl pillow numpy")
        return 1

    except Exception as e:
        print(f"Unexpected error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


def render_from_glsl(args: argparse.Namespace) -> int:
    """Render from an existing GLSL shader file (no AI generation)."""
    from .gif import save_gif, save_spritesheet, get_spritesheet_layout
    from .renderer import render_shader
    from .timing import get_timer, reset_timer

    shader_path = Path(args.prompt)
    if not shader_path.exists():
        print(f"Error: Shader file not found: {shader_path}")
        return 1

    # Read and strip any existing header
    shader_code = shader_path.read_text()
    shader_code = strip_glsl_header(shader_code)

    # Ensure output path has .gif extension
    output_path = args.output
    if not output_path.lower().endswith('.gif'):
        output_path += '.gif'

    print(f"Rendering from shader: {shader_path}")
    print(f"  Resolution: {args.resolution[0]}x{args.resolution[1]}")
    print(f"  Duration: {args.duration}s")
    print(f"  Frames: {args.frames}")
    if args.variations > 1:
        print(f"  Variations: {args.variations}")
    print(f"  Output: {output_path}")
    if args.spritesheet:
        cols, rows = get_spritesheet_layout(args.frames, args.rows)
        print(f"  Sprite sheet: {cols}x{rows} grid")
    print()

    reset_timer()
    timer = get_timer()
    timer.start()

    try:
        output_base = Path(output_path)

        if args.variations > 1:
            # Multiple variations
            for i in range(args.variations):
                variation_gif = output_base.with_stem(f"{output_base.stem}-{i}")
                print(f"  Rendering variation {i}...")

                with timer.phase(f"render_shader (variation {i}, {args.frames} frames)"):
                    frames = render_shader(
                        shader_code=shader_code,
                        duration=args.duration,
                        resolution=args.resolution,
                        num_frames=args.frames,
                        seed=float(i)
                    )

                with timer.phase(f"save_gif (variation {i})"):
                    save_gif(frames, str(variation_gif), args.duration)
                print(f"  GIF: {variation_gif}")

                if args.spritesheet:
                    spritesheet_path = variation_gif.with_suffix('.png')
                    cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                    print(f"  Sprite sheet: {spritesheet_path}")
        else:
            # Single output
            print("  Rendering...")
            with timer.phase(f"render_shader ({args.frames} frames)"):
                frames = render_shader(
                    shader_code=shader_code,
                    duration=args.duration,
                    resolution=args.resolution,
                    num_frames=args.frames,
                    seed=0.0
                )

            with timer.phase("save_gif"):
                save_gif(frames, output_path, args.duration)
            print(f"  GIF: {output_path}")

            if args.spritesheet:
                spritesheet_path = Path(output_path).with_suffix('.png')
                cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                sheet_width = cols * args.resolution[0]
                sheet_height = rows * args.resolution[1]
                print(f"  Sprite sheet: {spritesheet_path} ({sheet_width}x{sheet_height}, {cols}x{rows} grid)")

        print()
        print("Done!")
        print(timer.summary())
        return 0

    except Exception as e:
        print(f"Error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


async def run_edit_async(args: argparse.Namespace) -> int:
    """Run the VFX editing asynchronously."""
    from .agent import edit_vfx
    from .gif import save_gif, save_spritesheet, get_spritesheet_layout
    from .renderer import render_shader
    from .timing import get_timer, reset_timer

    # Read the existing shader
    shader_path = Path(args.edit)
    if not shader_path.exists():
        print(f"Error: Shader file not found: {shader_path}")
        return 1

    existing_shader = shader_path.read_text()
    existing_shader = strip_glsl_header(existing_shader)

    # Ensure output path has .gif extension
    output_path = args.output
    if not output_path.lower().endswith('.gif'):
        output_path += '.gif'

    print(f"Editing shader: {shader_path}")
    print(f"  Modification: {args.prompt}")
    print(f"  Resolution: {args.resolution[0]}x{args.resolution[1]}")
    print(f"  Duration: {args.duration}s")
    print(f"  Frames: {args.frames}")
    print(f"  Mode: {'looping' if args.loop else 'one-shot (dissipates)'}")
    if args.model:
        print(f"  Model: {args.model}")
    print(f"  Output: {output_path}")
    if args.spritesheet:
        cols, rows = get_spritesheet_layout(args.frames, args.rows)
        print(f"  Sprite sheet: {cols}x{rows} grid")
    print()

    reset_timer()
    timer = get_timer()
    timer.start()

    try:
        result = await edit_vfx(
            existing_shader=existing_shader,
            modification=args.prompt,
            duration=args.duration,
            resolution=args.resolution,
            frames=args.frames,
            output_path=output_path,
            verbose=args.verbose,
            loop=args.loop,
            model=args.model
        )

        if result["success"]:
            print()
            print("Success!")

            shader_code = result.get("shader_code")
            output_base = Path(output_path)

            print(f"  GIF: {result['gif_path']}")
            print(f"  Shader: {result['shader_path']}")

            # Generate sprite sheet if requested
            if args.spritesheet and shader_code:
                spritesheet_path = Path(output_path).with_suffix('.png')
                print(f"  Generating sprite sheet...")

                frames = render_shader(
                    shader_code=shader_code,
                    duration=args.duration,
                    resolution=args.resolution,
                    num_frames=args.frames
                )

                cols, rows = save_spritesheet(frames, str(spritesheet_path), args.rows)
                sheet_width = cols * args.resolution[0]
                sheet_height = rows * args.resolution[1]
                print(f"  Sprite sheet: {spritesheet_path} ({sheet_width}x{sheet_height}, {cols}x{rows} grid)")

            # Re-save shader with header comments
            new_shader_path = Path(output_path).with_suffix('.glsl')
            if shader_code and new_shader_path.exists():
                # For edit mode, use a modified generate command format
                generate_cmd = f"autofx --edit {shlex.quote(str(shader_path))} {shlex.quote(args.prompt)}"
                if args.duration != 1.0:
                    generate_cmd += f" -d {args.duration}"
                if args.resolution != (256, 256):
                    generate_cmd += f" -r {args.resolution[0]}x{args.resolution[1]}"
                if args.frames != 10:
                    generate_cmd += f" -f {args.frames}"
                if args.loop:
                    generate_cmd += " --loop"
                generate_cmd += f" -o {shlex.quote(args.output)}"

                render_cmd = build_render_command(str(new_shader_path), args)
                shader_with_header = add_glsl_header(shader_code, generate_cmd, render_cmd)
                new_shader_path.write_text(shader_with_header)

            print(timer.summary())
            return 0
        else:
            print()
            print(f"Error: {result['error']}")
            return 1

    except ImportError as e:
        print(f"Error: {e}")
        print()
        print("Make sure you have the required dependencies installed:")
        print("  pip install claude-agent-sdk moderngl pillow numpy")
        return 1

    except Exception as e:
        print(f"Unexpected error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


def main() -> int:
    """Main entry point for the CLI."""
    parser = create_parser()
    args = parser.parse_args()

    # Validate arguments
    if args.duration <= 0:
        print("Error: Duration must be positive")
        return 1

    if args.frames <= 0:
        print("Error: Frames must be positive")
        return 1

    if args.frames < 2:
        print("Warning: Using only 1 frame won't produce an animation")

    # Check mode: edit, render, or generate
    if args.edit:
        # Edit mode: modify existing shader with AI
        return asyncio.run(run_edit_async(args))
    elif args.prompt.lower().endswith('.glsl'):
        # Render mode: read shader and render directly
        return render_from_glsl(args)
    else:
        # Generate mode: use AI to create shader
        return asyncio.run(run_async(args))


if __name__ == "__main__":
    sys.exit(main())
