// Generated by: autofx 'fiery explosion' -f 30 -o examples/tweakable/explosion.gif
// Render with:  autofx examples/tweakable/explosion.glsl -d 1.0 -r 256x256 -f 30 -o examples/tweakable/explosion.gif

// @param fireballSize float 0.30 [0.18, 0.32] "Maximum fireball radius as a fraction of the frame"
// @param peakTime float 0.25 [0.12, 0.45] "Time of peak brightness as a fraction of the duration"
// @param intensity float 1.0 [0.6, 2.0] "Overall brightness and glow"
// @param turbulence float 1.0 [0.0, 2.0] "How much the fireball boils and churns"
// @param coreColor color #fff4d0 "Color of the hottest part of the fire"
// @param fireColor color #ff6a10 "Mid-temperature flame color"
// @param smokeColor color #2a201c "Color of the cooling smoke"
// @param sparkCount int 40 [0, 80] "Number of flying sparks"

float hash11(float p) { p = fract(p * 0.1031); p *= p + 33.33; p *= p + p; return fract(p); }

vec3 hash33(vec3 p) {
    p = fract(p * vec3(0.1031, 0.1030, 0.0973));
    p += dot(p, p.yxz + 33.33);
    return fract((p.xxy + p.yxx) * p.zyx) * 2.0 - 1.0;
}

float gnoise(vec3 p) {
    vec3 i = floor(p), f = fract(p);
    vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    return mix(mix(mix(dot(hash33(i), f),
                       dot(hash33(i + vec3(1,0,0)), f - vec3(1,0,0)), u.x),
                   mix(dot(hash33(i + vec3(0,1,0)), f - vec3(0,1,0)),
                       dot(hash33(i + vec3(1,1,0)), f - vec3(1,1,0)), u.x), u.y),
               mix(mix(dot(hash33(i + vec3(0,0,1)), f - vec3(0,0,1)),
                       dot(hash33(i + vec3(1,0,1)), f - vec3(1,0,1)), u.x),
                   mix(dot(hash33(i + vec3(0,1,1)), f - vec3(0,1,1)),
                       dot(hash33(i + vec3(1,1,1)), f - vec3(1,1,1)), u.x), u.y), u.z);
}

float fbm(vec3 p) {
    float s = 0.0, a = 0.5;
    for (int i = 0; i < 6; i++) {
        s += a * gnoise(p);
        p = p * 2.03 + vec3(1.7, -2.3, 0.9);
        a *= 0.5;
    }
    return s;
}

vec3 fireRamp(float h) {
    h = clamp(h, 0.0, 1.0);
    vec3 deep = fireColor * vec3(0.5, 0.1, 0.04);
    vec3 c = mix(vec3(0.0), deep, smoothstep(0.0, 0.2, h));
    c = mix(c, fireColor, smoothstep(0.15, 0.5, h));
    c = mix(c, mix(fireColor, coreColor, 0.55), smoothstep(0.5, 0.75, h));
    c = mix(c, coreColor, smoothstep(0.75, 1.0, h));
    return c;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 p = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float t = clamp(iTime, 0.0, 1.0);
    float seed = iSeed * 17.31;

    // Fast initial burst that decelerates.
    float grow = 1.0 - exp(-t * 7.0);
    float R = fireballSize * (0.15 + 0.85 * grow);

    // The plume lifts slightly as hot gas rises.
    float lift = 0.05 * t * t;
    vec2 q = p - vec2(0.0, lift);

    float heat = smoothstep(0.0, peakTime, t) * (1.0 - smoothstep(peakTime, 0.85, t));
    heat = pow(heat, 0.7);
    float life = 1.0 - smoothstep(0.5, 0.96, t);

    // Noise lives in fireball-relative space so the texture expands with the blast.
    vec3 np = vec3(q / max(R, 1e-3) * 2.4, t * 2.0 + seed);
    vec2 warp = vec2(fbm(np + vec3(3.1, 0.0, 0.0)), fbm(np + vec3(0.0, 5.7, 0.0)));
    float n = fbm(np * 1.4 + vec3(warp * 1.8 * turbulence, 0.0));
    float nn = clamp(n * 1.8, -1.0, 1.0);
    float d = length(q + warp * 0.03 * turbulence);

    // Billowy silhouette: edge displacement is bounded by 0.24 * fireballSize.
    vec3 ep = vec3(normalize(q + 1e-5) * 2.5, t * 1.2 + seed + 9.0);
    float en = clamp(fbm(ep) * 2.0 + nn * 0.5, -1.0, 1.0);
    float edge = R * (1.0 + (0.06 + 0.09 * turbulence) * en);
    float dens = 1.0 - smoothstep(edge * 0.8, edge, d);
    // Puffs eat into the ball as it cools.
    float erosion = smoothstep(0.3, 0.92, t);
    float puffs = smoothstep(-0.1, 0.2, nn * 0.7 + 0.45 - erosion * 0.75 + (1.0 - d / max(edge, 1e-3)) * 0.35);
    dens *= mix(1.0, puffs, erosion * 0.9 + 0.1);

    float core = 1.0 - smoothstep(0.0, edge, d);
    float temp = (0.2 + 0.5 * core + 0.6 * nn) * heat;
    temp = clamp(temp * intensity, 0.0, 1.3);

    vec3 fire = fireRamp(temp) * (0.7 + 0.6 * temp);
    float smokeAmt = smoothstep(0.45, 0.05, temp) * smoothstep(0.1, 0.4, t);
    vec3 col = mix(fire, smokeColor * (0.8 + 0.5 * nn), smokeAmt);
    float alpha = dens * life * smoothstep(0.0, 0.05, t);
    alpha *= mix(1.0, 0.9, smokeAmt);

    // Initial flash.
    float flashT = exp(-t * 20.0) * smoothstep(0.0, 0.02, t);
    float flash = flashT * exp(-dot(p, p) / (fireballSize * fireballSize * 0.3));
    col += coreColor * flash * 2.0 * intensity;
    alpha = max(alpha, clamp(flash * 1.5, 0.0, 1.0));

    // Shockwave ring.
    float ringR = fireballSize * 1.2 * (1.0 - exp(-t * 9.0));
    float ringA = exp(-pow((length(p) - ringR) / 0.008, 2.0)) * exp(-t * 11.0) * smoothstep(0.0, 0.03, t);
    col = mix(col, mix(fireColor, coreColor, 0.5) * 1.4 * intensity, clamp(ringA, 0.0, 1.0) * (1.0 - alpha));
    alpha = max(alpha, clamp(ringA, 0.0, 1.0));

    // Ballistic embers: drag-limited travel keeps them within ~0.44 of center.
    vec3 sparkCol = vec3(0.0);
    float sparkA = 0.0;
    for (int i = 0; i < 80; i++) {
        if (i >= sparkCount) break;
        float fi = float(i) + seed;
        float a = hash11(fi * 1.37) * 6.2831853;
        float spd = 0.35 + 0.5 * hash11(fi * 2.91);
        float lifeS = 0.45 + 0.4 * hash11(fi * 4.17);
        float st = t / lifeS;
        if (st > 1.0) continue;
        vec2 dir = vec2(cos(a), sin(a));
        float travel = spd * 0.42 * (1.0 - exp(-st * 3.0));
        vec2 pos = dir * travel - vec2(0.0, 0.08 * st * st);
        vec2 vel = dir * spd * 1.26 * exp(-st * 3.0) - vec2(0.0, 0.16 * st);
        vec2 rel = p - pos;
        vec2 vd = normalize(vel + 1e-5);
        float along = dot(rel, vd);
        float perp = dot(rel, vec2(-vd.y, vd.x));
        float len = 0.004 + 0.03 * length(vel);
        float s = exp(-pow(perp / 0.0035, 2.0)) * exp(-pow(max(-along, 0.0) / len, 2.0) - pow(max(along, 0.0) / 0.004, 2.0));
        float fade = (1.0 - st) * smoothstep(0.0, 0.05, st);
        s *= fade;
        sparkCol += mix(fireColor, coreColor, fade) * s * 1.6 * intensity;
        sparkA += s;
    }
    col += sparkCol;
    alpha = clamp(max(alpha, clamp(sparkA, 0.0, 1.0)), 0.0, 1.0);

    // Guarantees full transparency at the end of the duration.
    float endFade = 1.0 - smoothstep(0.9, 0.98, t);
    alpha *= endFade;
    col *= endFade;

    fragColor = vec4(col, alpha);
}
