// Generated by: autofx 'torch flame' -f 30 --loop -o examples/tweakable/torch.gif
// Render with:  autofx examples/tweakable/torch.glsl -d 1.0 -r 256x256 -f 30 --loop -o examples/tweakable/torch.gif

// @param flameSpeed int 2 [1, 4] "Upward flow cycles per loop"
// @param flameHeight float 0.5 [0.3, 0.6] "Flame height as a fraction of the frame"
// @param flameWidth float 0.13 [0.08, 0.18] "Half-width of the flame base"
// @param intensity float 1.0 [0.4, 1.6] "Overall brightness and glow"
// @param turbulence float 0.6 [0.15, 1.0] "How much the flame tongues churn"
// @param coreColor color #fff3c4 "Color of the hottest part of the flame"
// @param midColor color #ffa020 "Color of the flame body"
// @param edgeColor color #d42800 "Color at the flame edges"
// @param emberCount int 10 [0, 24] "Number of rising embers"
// @param showHandle bool true "Draw the wooden torch handle"

#define TAU 6.28318530718
const float PER = 8.0; // vertical noise period in cells

float hash21(vec2 p) {
    p = fract(p * vec2(123.34, 456.21) + iSeed * 0.137);
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

// Value noise that tiles vertically with period `per` cells, so vertical scrolling loops.
float tnoise(vec2 p, float per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float y0 = mod(i.y, per);
    float y1 = mod(i.y + 1.0, per);
    float a = hash21(vec2(i.x, y0));
    float b = hash21(vec2(i.x + 1.0, y0));
    float c = hash21(vec2(i.x, y1));
    float d = hash21(vec2(i.x + 1.0, y1));
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

// FBM whose every octave scrolls upward by a whole number of periods per loop.
float flowFbm(vec2 p, float ph) {
    float sum = 0.0, amp = 0.5, freq = 1.0, per = PER;
    for (int o = 0; o < 6; o++) {
        float cyc = float(flameSpeed) * (1.0 + float(o / 2));
        vec2 q = p * freq;
        q.y -= ph * per * cyc;
        q.x += float(o) * 17.3;
        sum += amp * tnoise(q, per);
        freq *= 2.0;
        per *= 2.0;
        amp *= 0.5;
    }
    return sum;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    float ph = fract(iTime);
    float ang = ph * TAU;

    float baseY = -0.2;
    float H = flameHeight;
    vec3 col = vec3(0.0);
    float alpha = 0.0;

    // Normalised flame coordinates: h in [0,1] from base to tip.
    float h = (uv.y - baseY) / H;
    vec2 np = vec2(uv.x / H * 4.0, h * PER * 0.5);

    // Gentle whole-flame sway, stronger towards the tip.
    float sway = (0.025 * sin(ang + h * 2.5) + 0.012 * sin(2.0 * ang - h * 5.0 + 1.3)) * smoothstep(0.0, 1.0, h);
    float x = uv.x - sway;

    float n1 = flowFbm(np, ph);
    float n2 = flowFbm(np * vec2(1.7, 1.0) + vec2(5.2, 0.0), ph);
    float hc = clamp(h, 0.0, 1.0);
    x += (n2 - 0.5) * turbulence * 0.12 * (0.3 + hc);

    // Teardrop silhouette: wide rounded base, tapering tip.
    float prof = flameWidth * pow(max(1.0 - hc, 0.0), 0.75) * (0.55 + 0.9 * sqrt(hc) * (1.0 - hc) + 0.45 * (1.0 - hc));
    float bottomRound = sqrt(max(0.0, 1.0 - pow(min(h, 0.0) / 0.12, 2.0)));
    prof *= (h < 0.0) ? bottomRound : 1.0;
    float d = abs(x) / max(prof, 1e-4);

    // Noise eats the flame edges and upper body into tongues.
    float erosion = (n1 - 0.5) * turbulence * (0.9 + 1.8 * hc) * (0.5 + min(d, 1.0));
    float dens = 1.0 - d - erosion - pow(hc, 3.0) * 0.6;
    dens *= smoothstep(-0.12, 0.0, h) * (1.0 - smoothstep(0.97, 1.0, h));
    dens = clamp(dens, 0.0, 1.0);

    float heat = clamp(dens * 1.35 - hc * 0.55, 0.0, 1.0);
    vec3 fcol = mix(edgeColor, midColor, smoothstep(0.05, 0.45, heat));
    fcol = mix(fcol, coreColor, smoothstep(0.6, 0.95, heat));
    float fa = smoothstep(0.0, 0.12, dens);
    // Intensity below 1 thins the flame; above 1 brightens it.
    float opac = min(intensity, 1.0);
    float bright = 1.0 + 0.5 * max(intensity - 1.0, 0.0);
    col += fcol * fa * opac * bright * (0.75 + 0.35 * heat);
    alpha = max(alpha, fa * opac);

    // Soft glow halo around the flame.
    vec2 gc = vec2(0.0, baseY + H * 0.3);
    float gd = length((uv - gc) * vec2(1.0, 0.7));
    float glow = exp(-gd * gd / (H * H * 0.09)) * 0.35 * intensity * (0.9 + 0.1 * sin(ang * 3.0));
    col += midColor * glow * (1.0 - fa);
    alpha = max(alpha, clamp(glow, 0.0, 1.0));

    // Torch handle: tapered wooden stick with a wrapped head.
    if (showHandle) {
        float top = baseY - 0.02, bot = -0.46;
        float t = clamp((top - uv.y) / (top - bot), 0.0, 1.0);
        float hw = mix(0.045, 0.028, t);
        if (uv.y < top + 0.02 && uv.y > bot && abs(uv.x) < hw) {
            float wood = 0.5 + 0.5 * sin(uv.x * 140.0 + tnoise(vec2(uv.x * 40.0, uv.y * 6.0), 1e4) * 4.0);
            vec3 hcol = mix(vec3(0.22, 0.12, 0.06), vec3(0.38, 0.22, 0.11), wood);
            hcol *= 0.6 + 0.6 * (1.0 - abs(uv.x) / hw);
            // Wrapped cloth bands near the top.
            if (uv.y > top - 0.07) {
                float band = step(0.5, fract((uv.y + uv.x * 0.6) * 45.0));
                hcol = mix(vec3(0.16, 0.09, 0.05), vec3(0.3, 0.2, 0.12), band);
            }
            // Firelight on the stick.
            hcol += midColor * 0.45 * exp(-(top - uv.y) * 12.0) * intensity;
            float ha = smoothstep(0.0, 0.004, hw - abs(uv.x));
            col = mix(col, hcol, ha);
            alpha = max(alpha, ha);
        }
    }

    // Rising embers on looping paths that fade out before leaving the frame.
    for (int i = 0; i < 24; i++) {
        if (i >= emberCount) break;
        float fi = float(i);
        float r1 = hash21(vec2(fi, 3.7));
        float r2 = hash21(vec2(fi, 9.1));
        float r3 = hash21(vec2(fi, 1.3));
        float life = fract(ph * float(1 + i % 2) + r1);
        float ey = baseY + H * 0.35 + life * (0.38 - H * 0.2);
        float ex = (r2 - 0.5) * flameWidth * 1.4 + 0.05 * sin(life * 6.0 + r3 * TAU) * life;
        float sz = 0.004 + 0.003 * r3;
        float dd = length(uv - vec2(ex, ey));
        float fade = smoothstep(0.0, 0.1, life) * (1.0 - smoothstep(0.55, 1.0, life));
        float e = exp(-dd * dd / (sz * sz)) * fade;
        vec3 ec = mix(coreColor, edgeColor, life);
        col += ec * e * 1.5 * intensity;
        alpha = max(alpha, clamp(e * 1.5, 0.0, 1.0));
    }

    // Colors are accumulated premultiplied; output straight alpha.
    alpha = clamp(alpha, 0.0, 1.0);
    vec3 rgb = alpha > 1e-4 ? col / alpha : vec3(0.0);
    fragColor = vec4(min(rgb, vec3(1.0)), alpha);
}